name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O usa 'master' dependiendo de tu configuración

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Asegúrate de usar la versión de Node que estás utilizando

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./dist/navidad-tarjetas  # Cambia esto al nombre correcto de tu carpeta de build

